FROM golang as builder

FROM scratch

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY bin/github-token-sidecar /github-token-sidecar

USER nobody

ENTRYPOINT ["/github-token-sidecar"]